export const ALGERIA_WILAYAS = [
    "Adrar",
    "Chlef",
    "Laghouat",
    "Oum El Bouaghi",
    "Batna",
    "Béjaïa",
    "Biskra",
    "Béchar",
    "Blida",
    "Bouira",
    "Tamanrasset",
    "Tébessa",
    "Tlemcen",
    "Tiaret",
    "Tizi Ouzou",
    "Alger",
    "Djelfa",
    "Jijel",
    "Sétif",
    "Saïda",
    "Skikda",
    "Sidi Bel Abbès",
    "Annaba",
    "Guelma",
    "Constantine",
    "Médéa",
    "Mostaganem",
    "M'Sila",
    "Mascara",
    "Ouargla",
    "Oran",
    "El Bayadh",
    "Illizi",
    "Bordj Bou Arreridj",
    "Boumerdès",
    "El Tarf",
    "Tindouf",
    "Tissemsilt",
    "El Oued",
    "Khenchela",
    "Souk Ahras",
    "Tipaza",
    "Mila",
    "Aïn Defla",
    "Naâma",
    "Aïn Témouchent",
    "Ghardaïa",
    "Relizane",
    "Timimoun",
    "Bordj Badji Mokhtar",
    "Ouled Djellal",
    "Béni Abbès",
    "In Salah",
    "In Guezzam",
    "Touggourt",
    "Djanet",
    "El M'Ghair",
    "El Meniaa"
];

// Simulate some communes for UX demo, to be populated from a JSON API
export const COMMUNES_BY_WILAYA: Record<string, string[]> = {
    Alger: ["Alger Centre", "Sidi M'Hamed", "El Madania", "Bab El Oued", "Oued Koriche", "Bologhine", "Hussein Dey", "Kouba", "El Biar", "Hydra", "Ben Aknoun", "Draria", "Baba Hassen", "Douera", "Cheraga", "Zeralda", "Rouiba", "Reghaia", "Dar El Beida", "Bab Ezzouar", "Bordj El Kiffan"],
    Oran: ["Oran", "Bir El Djir", "Es Senia", "Arzew", "Canastel"],
    Constantine: ["Constantine", "El Khroub", "Ain Smara", "Zighoud Youcef"],
    Blida: ["Blida", "Bouarfa", "Beni Mered", "Boufarik"],
    Sétif: ["Sétif", "El Eulma", "Ain Oulmene", "Ain Arnat"]
};
