export type MarketplaceCategory = {
    slug: string;
    name: string;
    iconSlug: string;
    enableDropdown?: boolean;
    subcategories: {
        slug: string;
        name: string;
        iconSlug?: string;
    }[];
};

export type MarketplaceArtisan = {
    id: string;
    name: string;
    categorySlug: string;
    categoryLabel: string;
    serviceTitle: string;
    profession?: string;
    specialties?: string[];
    age?: number | null;
    wilaya: string;
    commune: string;
    isVerified: boolean;
    planType?: string;
    ratingAvg: number;
    reviewsCount: number;
    phone: string;
    email?: string;
    avatarUrl: string;
    badges?: string[];
};

export const featuredCategories: MarketplaceCategory[] = [
    {
        slug: "plomberie-gaz",
        name: "Plomberie",
        iconSlug: "Wrench",
        enableDropdown: true,
        subcategories: [
            { slug: "fuite", name: "Reparation fuite" },
            { slug: "debouchage", name: "Debouchage canalisation" },
            { slug: "chauffe-eau", name: "Chauffe-eau" },
            { slug: "installation-sanitaire", name: "Installation sanitaire" },
            { slug: "robinetterie", name: "Robinetterie" },
            { slug: "tuyauterie", name: "Tuyauterie PPR cuivre" },
            { slug: "salle-de-bain", name: "Renovation salle de bain" },
            { slug: "pompe", name: "Pompe a eau et citerne" },
            { slug: "chauffage-central", name: "Chauffage central" },
            { slug: "gaz", name: "Installation et detection gaz" },
        ],
    },
    {
        slug: "electricite",
        name: "Electricite",
        iconSlug: "Zap",
        enableDropdown: true,
        subcategories: [
            { slug: "batiment", name: "Electricite batiment" },
            { slug: "industrielle", name: "Electricite industrielle" },
            { slug: "tableau-electrique", name: "Tableau electrique" },
            { slug: "depannage", name: "Depannage electrique" },
            { slug: "eclairage", name: "Eclairage et luminaires" },
            { slug: "interphone", name: "Interphone et controle acces" },
            { slug: "solaire", name: "Solaire" },
            { slug: "domotique", name: "Domotique" },
            { slug: "groupe-electrogene", name: "Groupe electrogene" },
            { slug: "mise-a-la-terre", name: "Mise a la terre" },
        ],
    },
    {
        slug: "climatisation",
        name: "Climatisation & Froid",
        iconSlug: "Wrench",
        subcategories: [
            { slug: "installation-clim", name: "Installation climatiseur" },
            { slug: "maintenance-clim", name: "Maintenance climatisation" },
            { slug: "recharge-gaz-clim", name: "Recharge gaz clim" },
            { slug: "chambre-froide", name: "Chambre froide" },
            { slug: "frigoriste", name: "Froid commercial" },
            { slug: "ventilation", name: "Ventilation VMC" },
            { slug: "chauffage-reversible", name: "Chauffage reversible" },
            { slug: "reparation-frigo", name: "Reparation refrigerateur" },
        ],
    },
    {
        slug: "construction",
        name: "Maconnerie & Renovation",
        iconSlug: "Hammer",
        enableDropdown: true,
        subcategories: [
            { slug: "maconnerie", name: "Maconnerie generale" },
            { slug: "gros-oeuvre", name: "Gros oeuvre" },
            { slug: "renovation-complete", name: "Renovation complete" },
            { slug: "carrelage", name: "Carrelage et faience" },
            { slug: "placo", name: "Placoplatre" },
            { slug: "revetement", name: "Revetement" },
            { slug: "facade", name: "Facade et crepi" },
            { slug: "dalle-beton", name: "Dalle et beton" },
            { slug: "coffrage", name: "Coffrage et ferraillage" },
            { slug: "demolition", name: "Demolition" },
        ],
    },
    {
        slug: "peinture-decor",
        name: "Peinture & Decor",
        iconSlug: "Paintbrush",
        subcategories: [
            { slug: "peinture", name: "Peinture interieure" },
            { slug: "facade", name: "Peinture facade" },
            { slug: "decor", name: "Decor mural" },
            { slug: "enduit", name: "Enduit et lissage" },
            { slug: "papier-peint", name: "Papier peint" },
            { slug: "staff", name: "Staff et moulures" },
            { slug: "resine-sol", name: "Resine de sol" },
            { slug: "effet-decoratif", name: "Effets decoratifs" },
        ],
    },
    {
        slug: "menuiserie",
        name: "Menuiserie & Amenagement",
        iconSlug: "Hammer",
        enableDropdown: true,
        subcategories: [
            { slug: "bois", name: "Menuiserie bois" },
            { slug: "cuisine", name: "Cuisine sur mesure" },
            { slug: "dressing", name: "Placards et dressing" },
            { slug: "portes-bois", name: "Portes bois" },
            { slug: "parquet", name: "Parquet et habillage bois" },
            { slug: "escaliers-bois", name: "Escaliers bois" },
            { slug: "fenetres-bois", name: "Fenetres bois" },
            { slug: "meubles", name: "Meubles sur mesure" },
        ],
    },
    {
        slug: "aluminium-pvc",
        name: "Aluminium & PVC",
        iconSlug: "Hammer",
        subcategories: [
            { slug: "fenetres-pvc", name: "Fenetres PVC" },
            { slug: "portes-pvc", name: "Portes PVC" },
            { slug: "baies-vitrees", name: "Baies vitrees" },
            { slug: "veranda", name: "Veranda" },
            { slug: "volets-roulants", name: "Volets roulants" },
            { slug: "moustiquaires", name: "Moustiquaires" },
            { slug: "facades-magasin", name: "Facades magasin" },
            { slug: "cloisons-alu", name: "Cloisons aluminium" },
        ],
    },
    {
        slug: "ferronnerie-inox",
        name: "Ferronnerie & Inox",
        iconSlug: "Hammer",
        subcategories: [
            { slug: "portails", name: "Portails" },
            { slug: "garde-corps", name: "Garde-corps" },
            { slug: "escaliers-metalliques", name: "Escaliers metalliques" },
            { slug: "soudure", name: "Soudure" },
            { slug: "charpente-metallique", name: "Charpente metallique" },
            { slug: "pergola", name: "Pergola et marquise" },
            { slug: "rideaux-metalliques", name: "Rideaux metalliques" },
            { slug: "inox-decoratif", name: "Inox decoratif" },
        ],
    },
    {
        slug: "toiture-etancheite",
        name: "Toiture & Etancheite",
        iconSlug: "Hammer",
        subcategories: [
            { slug: "etancheite-toiture", name: "Etancheite toiture" },
            { slug: "toiture-tuile", name: "Toiture tuile" },
            { slug: "charpente-toit", name: "Charpente toiture" },
            { slug: "zinguerie", name: "Zinguerie et gouttiere" },
            { slug: "isolation-terrasse", name: "Isolation terrasse" },
            { slug: "traitement-humidite", name: "Traitement humidite" },
            { slug: "bardage", name: "Bardage" },
            { slug: "reparation-fissure", name: "Reparation fissure" },
        ],
    },
    {
        slug: "vitrerie",
        name: "Vitrerie & Facades",
        iconSlug: "Monitor",
        subcategories: [
            { slug: "vitrerie", name: "Vitrerie" },
            { slug: "double-vitrage", name: "Double vitrage" },
            { slug: "miroiterie", name: "Miroiterie" },
            { slug: "douche-verre", name: "Paroi de douche en verre" },
            { slug: "vitrine-magasin", name: "Vitrine magasin" },
            { slug: "film-solaire", name: "Film solaire" },
            { slug: "facade-rideau", name: "Facade rideau" },
            { slug: "reparation-vitre", name: "Reparation vitre" },
        ],
    },
    {
        slug: "informatique",
        name: "Freelance & Digital",
        iconSlug: "Laptop",
        enableDropdown: true,
        subcategories: [
            { slug: "developpement-web", name: "Developpement Web", iconSlug: "Laptop" },
            { slug: "application-mobile", name: "Application mobile", iconSlug: "Laptop" },
            { slug: "ui-ux", name: "UI/UX Design", iconSlug: "Paintbrush" },
            { slug: "marketing", name: "Marketing Digital", iconSlug: "Megaphone" },
            { slug: "redaction", name: "Redaction Contenu", iconSlug: "PenLine" },
            { slug: "seo-sea", name: "SEO / SEA", iconSlug: "Megaphone" },
            { slug: "community-management", name: "Community management", iconSlug: "Megaphone" },
            { slug: "graphisme", name: "Graphisme", iconSlug: "Paintbrush" },
            { slug: "montage-video", name: "Montage video", iconSlug: "Camera" },
            { slug: "cybersecurite", name: "Cybersecurite", iconSlug: "Monitor" },
        ],
    },
    {
        slug: "telecom-reseaux",
        name: "Telecom & Reseaux",
        iconSlug: "Monitor",
        subcategories: [
            { slug: "fibre-optique", name: "Fibre optique" },
            { slug: "reseau-informatique", name: "Reseau informatique" },
            { slug: "cablage-structure", name: "Cablage structure" },
            { slug: "wifi-entreprise", name: "Wifi entreprise" },
            { slug: "videosurveillance-ip", name: "Videosurveillance IP" },
            { slug: "pointage", name: "Pointage et acces" },
            { slug: "standard-telephonique", name: "Standard telephonique" },
            { slug: "maintenance-reseau", name: "Maintenance reseau" },
        ],
    },
    {
        slug: "couture",
        name: "Couture & Reparation",
        iconSlug: "ScissorsSquare",
        subcategories: [
            { slug: "retouche", name: "Retouche vetements" },
            { slug: "tailleur", name: "Tailleur" },
            { slug: "broderie", name: "Broderie" },
            { slug: "couture-traditionnelle", name: "Tenues traditionnelles" },
            { slug: "rideaux", name: "Rideaux sur mesure" },
            { slug: "linge-maison", name: "Linge de maison" },
            { slug: "uniformes", name: "Uniformes professionnels" },
            { slug: "patronage", name: "Patronage et modelisme" },
        ],
    },
    {
        slug: "beaute",
        name: "Coiffeur a domicile",
        iconSlug: "Scissors",
        subcategories: [
            { slug: "coiffure", name: "Coiffure" },
            { slug: "maquillage", name: "Maquillage" },
            { slug: "onglerie", name: "Onglerie" },
            { slug: "barber", name: "Barber a domicile" },
            { slug: "coiffure-mariee", name: "Coiffure mariee" },
            { slug: "soin-visage", name: "Soin du visage" },
            { slug: "epilation", name: "Epilation" },
            { slug: "esthetique", name: "Esthetique generale" },
        ],
    },
    {
        slug: "restauration",
        name: "Traiteur & Chef",
        iconSlug: "ChefHat",
        enableDropdown: true,
        subcategories: [
            { slug: "traiteur", name: "Traiteur" },
            { slug: "gateaux", name: "Gateaux traditionnels" },
            { slug: "cuisinier", name: "Cuisinier a domicile" },
            { slug: "patisserie", name: "Patisserie" },
            { slug: "buffet-entreprise", name: "Buffet entreprise" },
            { slug: "barbecue", name: "Barbecue et mechoui" },
            { slug: "repas-diet", name: "Repas dietetiques" },
            { slug: "livraison-plateaux", name: "Livraison plateaux repas" },
        ],
    },
    {
        slug: "mecanique-auto",
        name: "Mecanique mobile",
        iconSlug: "Car",
        subcategories: [
            { slug: "scanner", name: "Diagnostic" },
            { slug: "electricite", name: "Electricite auto" },
            { slug: "depannage", name: "Depannage" },
            { slug: "vidange", name: "Vidange et entretien" },
            { slug: "freinage", name: "Freinage et suspension" },
            { slug: "carrosserie", name: "Carrosserie et peinture" },
            { slug: "clim-auto", name: "Climatisation auto" },
            { slug: "pneumatique", name: "Pneumatique" },
        ],
    },
    {
        slug: "electromenager-tv",
        name: "Electromenager & Electronique",
        iconSlug: "Monitor",
        subcategories: [
            { slug: "tv", name: "Reparation TV" },
            { slug: "machine-laver", name: "Machine a laver" },
            { slug: "refrigerateur", name: "Refrigerateur" },
            { slug: "four-cuisiniere", name: "Four et cuisiniere" },
            { slug: "lave-vaisselle", name: "Lave-vaisselle" },
            { slug: "petit-electro", name: "Petit electromenager" },
            { slug: "telephones", name: "Telephones et tablettes" },
            { slug: "decodeurs", name: "Recepteurs et decodeurs" },
        ],
    },
    {
        slug: "nettoyage",
        name: "Menage & Nettoyage",
        iconSlug: "Sparkles",
        subcategories: [
            { slug: "domicile", name: "Menage domicile" },
            { slug: "industriel", name: "Nettoyage industriel" },
            { slug: "desinsectisation", name: "Desinsectisation" },
            { slug: "fin-chantier", name: "Nettoyage fin de chantier" },
            { slug: "canape", name: "Nettoyage canape" },
            { slug: "tapis", name: "Lavage tapis" },
            { slug: "vitres", name: "Lavage vitres" },
            { slug: "desinfection", name: "Desinfection" },
        ],
    },
    {
        slug: "multiservices",
        name: "Reparation",
        iconSlug: "Hammer",
        enableDropdown: true,
        subcategories: [
            { slug: "serrurerie", name: "Serrurerie" },
            { slug: "antenne", name: "Installation antenne" },
            { slug: "bricolage", name: "Bricolage" },
            { slug: "montage-meubles", name: "Montage meubles" },
            { slug: "fixation-tv", name: "Fixation TV" },
            { slug: "petits-travaux", name: "Petits travaux" },
            { slug: "maintenance-immeuble", name: "Maintenance immeuble" },
            { slug: "depannage-urgent", name: "Depannage urgent" },
        ],
    },
    {
        slug: "formation",
        name: "Cours particuliers",
        iconSlug: "BookOpen",
        subcategories: [
            { slug: "soutien", name: "Soutien scolaire" },
            { slug: "langues", name: "Langues" },
            { slug: "musique", name: "Musique" },
            { slug: "informatique", name: "Informatique" },
            { slug: "formation-pro", name: "Formation pro" },
            { slug: "code-route", name: "Code de la route" },
            { slug: "coaching-sportif", name: "Coaching sportif" },
            { slug: "preparation-examens", name: "Preparation examens" },
        ],
    },
    {
        slug: "transport",
        name: "Demenagement",
        iconSlug: "Package",
        subcategories: [
            { slug: "demenagement", name: "Demenagement" },
            { slug: "manutention", name: "Manutention" },
            { slug: "transport", name: "Transport local" },
            { slug: "livraison-colis", name: "Livraison colis" },
            { slug: "camion-marchandises", name: "Camion marchandises" },
            { slug: "location-camion", name: "Location camion avec chauffeur" },
            { slug: "debarras", name: "Debarras" },
            { slug: "garde-meuble", name: "Garde meuble" },
        ],
    },
    {
        slug: "jardinage-agri",
        name: "Jardinage",
        iconSlug: "TreePine",
        subcategories: [
            { slug: "jardinier", name: "Jardinier" },
            { slug: "elagage", name: "Elagage" },
            { slug: "pepiniere", name: "Pepiniere" },
            { slug: "arrosage", name: "Arrosage" },
            { slug: "amenagement", name: "Amenagement paysager" },
            { slug: "entretien-espaces-verts", name: "Entretien espaces verts" },
            { slug: "traitement", name: "Traitement phytosanitaire" },
            { slug: "piscine", name: "Entretien piscine" },
        ],
    },
    {
        slug: "audiovisuel",
        name: "Photographe",
        iconSlug: "Camera",
        subcategories: [
            { slug: "photo", name: "Photographe" },
            { slug: "video", name: "Videaste" },
            { slug: "drone", name: "Pilote drone" },
            { slug: "streaming", name: "Streaming live" },
            { slug: "studio", name: "Studio photo" },
            { slug: "montage-video", name: "Montage video" },
            { slug: "retouche-photo", name: "Retouche photo" },
            { slug: "voix-off", name: "Voix-off et audio" },
        ],
    },
    {
        slug: "impression",
        name: "Impression & Publicite",
        iconSlug: "Megaphone",
        subcategories: [
            { slug: "imprimerie", name: "Imprimerie" },
            { slug: "cartes-visite", name: "Cartes de visite" },
            { slug: "flyers", name: "Flyers et brochures" },
            { slug: "enseignes", name: "Enseignes" },
            { slug: "stickers", name: "Stickers vitrine" },
            { slug: "habillage", name: "Habillage facade et vehicule" },
            { slug: "goodies", name: "Goodies entreprise" },
            { slug: "serigraphie", name: "Serigraphie et flocage" },
        ],
    },
    {
        slug: "evenementiel",
        name: "Evenementiel",
        iconSlug: "Sparkles",
        subcategories: [
            { slug: "decoration", name: "Decoration evenement" },
            { slug: "location-salle", name: "Location salle" },
            { slug: "chapiteaux", name: "Chapiteaux et tentes" },
            { slug: "chaises-tables", name: "Chaises et tables" },
            { slug: "sonorisation", name: "Sonorisation" },
            { slug: "eclairage-scene", name: "Eclairage scene" },
            { slug: "dj-animation", name: "DJ et animation" },
            { slug: "wedding-planner", name: "Wedding planner" },
        ],
    },
    {
        slug: "juridique-admin",
        name: "Conseil & Juridique",
        iconSlug: "Scale",
        enableDropdown: true,
        subcategories: [
            { slug: "ecrivain", name: "Ecrivain public" },
            { slug: "traduction", name: "Traduction assermentee" },
            { slug: "comptabilite", name: "Comptabilite" },
            { slug: "visa", name: "Dossiers visa" },
            { slug: "creation-entreprise", name: "Creation entreprise" },
            { slug: "assistance-admin", name: "Assistance administrative" },
            { slug: "conseil-juridique", name: "Conseil juridique" },
            { slug: "redaction-contrats", name: "Redaction contrats" },
        ],
    },
    {
        slug: "sante-bien-etre",
        name: "Soins a domicile",
        iconSlug: "HeartPulse",
        enableDropdown: true,
        subcategories: [
            { slug: "garde-malade", name: "Garde-malade" },
            { slug: "kine", name: "Kinesitherapie" },
            { slug: "aide-agees", name: "Aide personnes agees" },
            { slug: "infirmier", name: "Infirmier a domicile" },
            { slug: "garde-enfant", name: "Garde enfant" },
            { slug: "nutrition", name: "Nutrition" },
            { slug: "massage", name: "Massage bien-etre" },
            { slug: "hijama", name: "Hijama" },
        ],
    },
    {
        slug: "securite",
        name: "Securite & Surveillance",
        iconSlug: "Monitor",
        subcategories: [
            { slug: "videosurveillance", name: "Videosurveillance" },
            { slug: "alarme", name: "Alarme intrusion" },
            { slug: "controle-acces", name: "Controle acces" },
            { slug: "interphone-visiophone", name: "Interphone et visiophone" },
            { slug: "gardiennage", name: "Gardiennage" },
            { slug: "securite-evenement", name: "Securite evenementielle" },
            { slug: "coffre-fort", name: "Coffre-fort" },
            { slug: "incendie", name: "Detection incendie" },
        ],
    },
    {
        slug: "animaux",
        name: "Animaux & Veterinaire",
        iconSlug: "Heart",
        subcategories: [
            { slug: "veterinaire-domicile", name: "Veterinaire a domicile" },
            { slug: "toilettage", name: "Toilettage" },
            { slug: "dressage", name: "Dressage canin" },
            { slug: "garde-animaux", name: "Garde animaux" },
            { slug: "promenade", name: "Promenade chiens" },
            { slug: "nutrition-animale", name: "Nutrition animale" },
        ],
    },
    {
        slug: "immobilier",
        name: "Immobilier & Courtage",
        iconSlug: "PenLine",
        subcategories: [
            { slug: "agent-immobilier", name: "Agent immobilier" },
            { slug: "courtage", name: "Courtage" },
            { slug: "estimation", name: "Estimation immobiliere" },
            { slug: "location-gestion", name: "Location et gestion" },
            { slug: "etat-des-lieux", name: "Etat des lieux" },
            { slug: "home-staging", name: "Home staging" },
        ],
    },
];

export const featuredArtisans: MarketplaceArtisan[] = [
    {
        id: "artisan-krimo",
        name: "Krimo M.",
        categorySlug: "plomberie-gaz",
        categoryLabel: "Plomberie",
        serviceTitle: "Plombier sanitaire",
        wilaya: "Alger",
        commune: "Baba Hassen",
        isVerified: true,
        ratingAvg: 4.9,
        reviewsCount: 124,
        phone: "+213550110011",
        avatarUrl: "https://i.pravatar.cc/180?img=12",
    },
    {
        id: "artisan-amel",
        name: "Amel S.",
        categorySlug: "beaute",
        categoryLabel: "Beaute",
        serviceTitle: "Coiffure a domicile",
        wilaya: "Alger",
        commune: "Baba Hassen",
        isVerified: true,
        ratingAvg: 4.8,
        reviewsCount: 124,
        phone: "+213550220022",
        avatarUrl: "https://i.pravatar.cc/180?img=47",
    },
    {
        id: "artisan-nour",
        name: "Nour H.",
        categorySlug: "restauration",
        categoryLabel: "Restauration",
        serviceTitle: "Traiteur evenementiel",
        wilaya: "Alger",
        commune: "Baba Hassen",
        isVerified: true,
        ratingAvg: 4.9,
        reviewsCount: 124,
        phone: "+213550330033",
        avatarUrl: "https://i.pravatar.cc/180?img=32",
    },
    {
        id: "artisan-omar",
        name: "Omar K.",
        categorySlug: "construction",
        categoryLabel: "Construction",
        serviceTitle: "Macon renovation",
        wilaya: "Alger",
        commune: "Baba Hassen",
        isVerified: true,
        ratingAvg: 4.9,
        reviewsCount: 124,
        phone: "+213550440044",
        avatarUrl: "https://i.pravatar.cc/180?img=66",
    },
    {
        id: "artisan-samir",
        name: "Samir B.",
        categorySlug: "informatique",
        categoryLabel: "Freelance & Digital",
        serviceTitle: "Developpeur web freelance",
        wilaya: "Oran",
        commune: "Es Senia",
        isVerified: true,
        ratingAvg: 4.9,
        reviewsCount: 33,
        phone: "+213550550055",
        avatarUrl: "https://i.pravatar.cc/180?img=14",
    },
    {
        id: "artisan-lyna",
        name: "Lyna D.",
        categorySlug: "nettoyage",
        categoryLabel: "Menage & Nettoyage",
        serviceTitle: "Menage a domicile",
        wilaya: "Constantine",
        commune: "El Khroub",
        isVerified: true,
        ratingAvg: 4.8,
        reviewsCount: 19,
        phone: "+213550660066",
        avatarUrl: "https://i.pravatar.cc/180?img=45",
    },
];
